server:
  port: 8080

spring:
  application:
    name: user-management-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-management
    username: smile
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

jwt:
  secret: "dev-secret-change-me"
  issuer: "user-management-backend"
  expire-minutes: 720

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
